# Generated by Django 4.0.3 on 2022-03-10 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import internetdokon.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone', models.TextField(max_length=16, validators=[internetdokon.validators.PhoneValidator()])),
                ('zip_code', models.CharField(max_length=20)),
                ('status', models.SmallIntegerField(choices=[(0, 'NEW'), (1, 'ACCEPTED'), (2, 'REJECTED')])),
                ('order_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='common.country')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='common.district')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='common.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text_prefix', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('available', models.IntegerField(default=0)),
                ('status', models.SmallIntegerField(choices=[(1, 'Bor'), (0, 'Qolmagan')])),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.product')),
            ],
        ),
    ]
