# Generated by Django 4.0.3 on 2022-04-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='text_prefix',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='main_produc_status_5f94cf_idx'),
        ),
    ]
