# Generated by Django 4.0.3 on 2022-04-21 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
