# Generated by Django 4.0.3 on 2022-04-21 01:59

from django.db import migrations, models
import django.db.models.deletion
import internetdokon.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_product_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone', models.TextField(max_length=16, validators=[internetdokon.validators.PhoneValidator()])),
                ('zip_code', models.CharField(max_length=20)),
                ('status', models.SmallIntegerField(choices=[(1, 'Bor'), (0, "Yo'q")])),
                ('payment_status', models.SmallIntegerField(choices=[(0, 'New'), (1, 'Prepare'), (2, 'Complete')], default=0)),
                ('order_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cart.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.product')),
            ],
        ),
    ]
