# Generated by Django 4.0.3 on 2022-04-21 02:39

from django.db import migrations, models
import internetdokon.validators


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=16, validators=[internetdokon.validators.PhoneValidator()]),
        ),
    ]
