# Generated by Django 4.0.3 on 2022-04-21 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_orderproduct_order_and_more'),
        ('cart', '0003_alter_order_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProductModel',
            new_name='OrderProduct',
        ),
    ]
